name: "Fluxzero JWT"
description: "Generate a Fluxzero JWT to be used for logging into the registry or deploying an application"
author: fluxzero-io
branding:
  icon: unlock
  color: gray-dark

inputs:
  api-key:
    description: "Fluxzero API key"
    required: true
  validity-seconds:
    description: "Token validity in seconds"
    required: false
    default: "300"

outputs:
  token:
    description: "The generated JWT"
  userId:
    description: "The userId of the API key"

runs:
  using: "node20"
  main: "dist/index.js"
