name: Build and push

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
    paths-ignore:
      - 'dist/**'

permissions:
  contents: write

jobs:
  build-and-commit:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: autobuild-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run ci

      - name: Commit dist directory if changed
        run: |
          set -euo pipefail
          if ! git diff --quiet --exit-code dist; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add dist
            git commit -m "build: update dist for ${GITHUB_SHA::7} [skip ci]"
            git push
          else
            echo "No changes in dist directory"
          fi
